### ISSUE TITLE
Missing file: iscloam/LoopInfo.h

### ISSUE THREAD

**Issue by PaulKemppi** [wh200720041/iscloam#1]
Hi,

It would be nice to test the iscloam with my own data. Currently, the compilation fails due to missing iscloam/LoopInfo.h referenced in iscloam/src/iscOptimizationNode.cpp and iscGenerationNode.cpp.

Regards,
Paul

**Comment by wh200720041** [comment]
Hi Paul:
It seems that when you compile, the custom message loopinfo.msg is built after iscloam, the solution is let system build custom message first by add 

add_dependencies(iscloam_isc_optimization_node {${PROJECT_NAME}_EXPORTED_TARGETS})
in cmakelists.txt

The code is updated and you can download and try again

Let me know if the problem still happens.

Regards
Han

**Comment by PaulKemppi** [comment]
Yes that was it. Now it compiles without errors. Thank you for the quick reply!

Regards,
Paul
