### ISSUE TITLE
The traslational error on sequence 00 does not match that published on this page

### ISSUE THREAD

**Issue by HustCK** [wh200720041/iscloam#11]
Dear authors, firstly I want to thanks for your code. I have tested your code on sequence 00 of Kitti odometry dataset, and the result of average translational error is around 1.17%, which is not match 0.24% published on your github page. The same problem occurs in Fast-Loam, where your result is 0.51% on sequence 00 and my result is 0.97%. Maybe I need to make some changes to the code base you released before testing on Kitti odometry? I would be very grateful if you could help me.

**Comment by wh200720041** [comment]
Hi @CKkkkkkk 

Thanks for posting question.

The code is same, but there are some modifications on the evaluation methods. In the official website it is based on 400/800 frames. I changed to larger value. Because if we only measure the 400 frames the result of loop closure is not significant. 

Regards
Han

**Comment by CKkkkkkk** [comment]
Ok, I know, thanks for your answer very much!

**Comment by CKkkkkkk** [comment]
Dear author, I have tried according to your answer. When I adjust from 400/800 to 2000, I can get 0.25% result on kitti sequence 00. Thanks for your answer again. By the way, do you know why many lidar odometry and SLAM system (eg. A-LOAM, Fast-LOAM, ISC-LOAM, LeGO-LOAM) could not work well on Kitti odometry sequence 04? The translational error of them are around 1.5-2.5%. Could you tell me the reason if you know?

**Comment by wh200720041** [comment]
Hi @CKkkkkkk 

A possible answer is that the sequence 04 is too short, it only contains 270 frames.

Regards
Han

**Comment by caoyifeng001** [comment]
请问，你们用的计算精度的工具是哪个吗

**Comment by wh200720041** [comment]
> 请问，你们用的计算精度的工具是哪个吗

You may write your own evaluation tools, or download from kitti website

**Comment by caoyifeng001** [comment]
OK ,thanks for your reply

**Comment by caoyifeng001** [comment]
我把lengths 设为 [800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000]
floam的旋转精度为0.5696，  iscloam的旋转精度为0.4997%
这个和你设置的一样吗？

**Comment by wh200720041** [comment]
> 我把lengths 设为 [800,900,1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000]
> floam的旋转精度为0.5696， iscloam的旋转精度为0.4997%
> 这个和你设置的一样吗？

In my case I write own evaluation code. I think the result is same when you set your length to infinity.

**Comment by caoyifeng001** [comment]
感谢，我学到了很多。

**Comment by wh200720041** [comment]
If there is not further question I shall close this issue
