### ISSUE TITLE
Loopclosure seems doesn't work

### ISSUE THREAD

**Issue by kinggreat24** [wh200720041/iscloam#13]
Hi @wh200720041, thanks for sharing your excellent work!   I have some questions after running your code as follows:

- When loopclosure was detected,  the topic **/final_path** didn't output anymore. Red path is ground truth, Yellow path is result of **iscOptimizationClassNode.cpp**. 

  <center class="half"> 
![before_loopclosure](https://user-images.githubusercontent.com/30688557/92622849-1d8fdc80-f2f8-11ea-928b-f2fcac8fcac8.png)
![after_loopclosure](https://user-images.githubusercontent.com/30688557/92622869-22ed2700-f2f8-11ea-8897-539e3023273e.png)

 </center>

- The second is how to save all frame's pose in KITTI's format, the poses I got always lost some frames, can you give me some advices, and how did you evaluate accuracy in KITTI dataset?

Wish to get reply from you, and thanks for work sincerely.

**Comment by wh200720041** [comment]
Hi @kinggreat24 :

It takes a while for global optimization and loop closure detection. Hence the odometry and global optimization is running in a separate thread. Therefore, a certain delay is expected. You can wait for a while and I think path will be updated. Otherwise perhaps it is caused by GTSAM version issue, as you mentioned in another issue. I will take note of this and test a higher version of GTSAM to see if I can get the same problem.

For output of pose, it is simply a file writing function in cpp, there is a description file on how to generate and evaluate accuracy on KITTI website, you can read through that file. In the meanwhile, the evaluation code can also be downloaded from KITTI website. 

During my test I didn't experience the lost of frames. Perhaps you could give more details, like which topic you are using to record the pose.

Regards
Han

**Comment by kinggreat24** [comment]
Thank you for your prompt reply, I have tried to use GTSAM-3.2.3 to check  if it is due to version issues, but unfortunately I could not compile success with GTSAM-3.2.3 for some errors, such as 
-  error: could not convert ‘Eigen::DenseBase<Derived>::operator<<(const Scalar&) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseBase<Derived>::Scalar = double]((& dp)->gtsam::Point2::x()).Eigen::CommaInitializer<MatrixType>::operator,<Eigen::Matrix<double, -1, 1> >((& dp)->gtsam::Point2::y())’ from ‘Eigen::CommaInitializer<Eigen::Matrix<double, -1, 1> >’ to ‘gtsam::Vector {aka Eigen::Matrix<double, -1, 1>}’
- /usr/local/gtsam3.2.3/include/gtsam/geometry/Rot2.h:176:25: error: could not convert ‘Eigen::DenseBase<Derived>::operator<<(const Scalar&) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseBase<Derived>::Scalar = double]((& r)->gtsam::Rot2::theta())’ from ‘Eigen::CommaInitializer<Eigen::Matrix<double, -1, 1> >’ to ‘gtsam::Vector {aka Eigen::Matrix<double, -1, 1>}’
       return (Vector(1) << r.theta())
- /usr/local/gtsam3.2.3/include/gtsam/base/SymmetricBlockMatrix.h:119:43: error: no matching function for call to ‘gtsam::SymmetricBlockMatrixBlockExpr<gtsam::SymmetricBlockMatrix>::SymmetricBlockMatrixBlockExpr(gtsam::SymmetricBlockMatrix&, gtsam::DenseIndex&, gtsam::DenseIndex&)’
       return Block(*this, i_block, j_block);

and so on. Can you give me some advice?

**Comment by wh200720041** [comment]
Hi @kinggreat24 

For the compiling of GTSAM, I think you can search on Google. Because I didn't experience this error when compile my own gtsam.

Han

**Comment by kinggreat24** [comment]
Hi @wh200720041, I have replaced the gtsam with ceres, thanks for your help.

**Comment by yjsx** [comment]
Hi @kinggreat24 
It seems that I meet the same question, but I have no idea how to solve it. Do you remember what did you do? Thanks.

**Comment by kinggreat24** [comment]
I used Ceres instead of gtsam, you can try Ceres or g2o to optimize pose graph.



发自我的iPhone


------------------ Original ------------------

**Comment by yjsx** [comment]
ohoh, I see. Thank you! @kinggreat24

**Comment by kinggreat24** [comment]
If you failed to solve the problem, I can show you my code.



发自我的iPhone


------------------ Original ------------------

**Comment by yjsx** [comment]
Thank you very much. Let me have a try. If I fail, I will ask you for help

> If you failed to solve the problem, I can show you my code. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: yjsx <notifications@github.com&gt; Date: Sun,Dec 27,2020 6:18 PM To: wh200720041/iscloam <iscloam@noreply.github.com&gt; Cc: kinggreat24 <450993749@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [wh200720041/iscloam] Loopclosure seems doesn't work (#13) ohoh, I see. Thank you! @kinggreat24 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
