### ISSUE TITLE
cannot launch node of type [hector_trajectory_server/hector_trajectory_server]

### ISSUE THREAD

**Issue by Lyusijie** [wh200720041/iscloam#2]
Hello, when i do the second roslaunch, there is `ERROR: cannot launch node of type [hector_trajectory_server/hector_trajectory_server]: hector_trajectory_server
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/media/lvsijie/mypassport/linux/catkin_ws_iscloam/src
ROS path [2]=/opt/ros/kinetic/share
`
my system is ubuntu 16.04, it seems that there is no hector_trajectory_server.
Do i install hector-slam to get hector_trajectory_server?
thank you!

**Comment by Lyusijie** [comment]
i solved it by installing hector-slam, thank you

**Comment by wh200720041** [comment]
Yes you are right, for trajectory visualization you have to install 
sudo apt-get install ros-melodic-hector-trajectory-server
The readme is updated for the above problem
