### ISSUE TITLE
Map result iscloam

### ISSUE THREAD

**Issue by cristianrubioa** [wh200720041/iscloam#22]
Hi :) @wh200720041  I keep testing your algorithm.

When I get the map from iscloam I have a poor result compared to floam.
iscloam:
![Screen Shot 2021-04-16 at 6 08 46 AM](https://user-images.githubusercontent.com/44789319/115016075-35c16e80-9e7a-11eb-91ed-ff41a740903d.png)
floam:
![Screen Shot 2021-04-16 at 6 09 00 AM](https://user-images.githubusercontent.com/44789319/115016094-3e19a980-9e7a-11eb-8249-497e29cafceb.png)

I subscribe to /map and get a .pcd file. I test these two ways:
(1)
```
rosrun pcl_ros pointcloud_to_pcd input:=/map 
```
(2)

```
rosbag record -o <name> /map
rosrun pcl_ros bag_to_pcd <rosbag_name.bag> /map pcd
```

Your explanation will be of great help to me.

**Comment by Oyssster** [comment]
@cristianrubioa Hello, I can't run the code properly, so can you tell me the version of you PCL, Ceres and Gtsam?

**Comment by cristianrubioa** [comment]
@Oyssster Hello, the versions are.
PCL: 1.8
Ceres: 2.0
GTSAM: 4.0.3

**Comment by Oyssster** [comment]
> @Oyssster Hello, the versions are.
> PCL: 1.8
> Ceres: 2.0
> GTSAM: 4.0.3

It's so nice to receive this message. Thank you very much!

**Comment by cristianrubioa** [comment]
Solution to this issue:

Change "downsampling size" in "laserMappingClass.cpp"
