### ISSUE TITLE
loop closure index

### ISSUE THREAD

**Issue by narutojxl** [wh200720041/iscloam#8]
Hi doctor wang,
When `geometryConsistencyVerification()` in line 68 of iscOptimizationClass.cpp, return true, there is a true loop between history matched frame id and curr id. 
Why the code is this ?  Thanks for your help !
> 
	graph.push_back(
              gtsam::BetweenFactor<gtsam::Pose3>(gtsam::Symbol('x', matched_frame_id[i]+1), //TODO：why not is  matched_frame_id[i]
		                                 gtsam::Symbol('x', pointcloud_edge_arr.size()), //TODO: why not is  pointcloud_edge_arr.size()-1
		                                 loop_temp, loopModel));

**Comment by wh200720041** [comment]
Hi @narutojxl 

I think according to the gtsam tutorial, the first pose_id is 1 instead of 0,

You can find the example from here.
https://github.com/dongjing3309/gtsam-examples/blob/master/cpp/examples/Pose2SLAMExample.cpp

However, the array in cpp starts with 0, so here we need to add 1 to match the gtsam symbol.

Han

**Comment by narutojxl** [comment]
Hi doctor wang, 
Thanks for your help, i didn't notice the fisrt node is marked as `graph.push_back(gtsam::PriorFactor<gtsam::Pose3>(gtsam::Symbol('x', 1), pose_optimized_arr.front(), priorModel));` line 41 in code, thanks for your advice!
BTW, if we mark the origin node is `gtsam::Symbol('x', 0)`,  then we no need  plus 1, right?

**Comment by wh200720041** [comment]
Hi @narutojxl 

Yes I think so, but if you want to change this, you may have to change the corresponding ids in other function as well. However, it is not necessary to change this because changing ids does not affect the performance

**Comment by narutojxl** [comment]
Yes, i agree with you! Thanks doctor, my problem is solved.
